// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "23d1b83d-ca30-46f4-9e68-045f90b35c21");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1696777664);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1696777664);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1696777664);
user_pref("app.update.lastUpdateTime.region-update-timer", 1696777664);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1696777710);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1696777664);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1696777694);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1696777664);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{0894d8b8-5ed4-49f7-bd1b-8340edc1e112}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1696777632);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{611262ac-0f45-46bf-b3b1-de10a6995952}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1696777634);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1696777659530");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1696779429530");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1696777636926");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1696799236926");
user_pref("browser.search.region", "SE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1696777710");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230928170531");
user_pref("browser.startup.homepage_override.mstone", "118.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1696777709);
user_pref("browser.topsites.contile.lastFetch", 1696777710);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"keepassxc-browser_keepassxc_org-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"keepassxc-browser_keepassxc_org-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"unified-extensions-area\",\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1696777634657");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "118.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "SE");
user_pref("dom.push.userAgentID", "a25fcebade7d42b987d8be666e72321e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1696777665);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230928170531");
user_pref("extensions.lastAppVersion", "118.0.1");
user_pref("extensions.lastPlatformVersion", "118.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.keepassxc-browser@keepassxc.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"7c7ce5b9-b040-41a7-ada2-f4f59674db6c\",\"pictureinpicture@mozilla.org\":\"d2287a25-3652-48d4-8745-6911e9241a59\",\"screenshots@mozilla.org\":\"0ce54087-bd4b-449d-859f-5a19583adf36\",\"webcompat-reporter@mozilla.org\":\"dbd44fc8-a3a1-472f-a2b9-dd173974c01a\",\"webcompat@mozilla.org\":\"aef6acb1-cf91-4d19-8e10-ee6ad5af2519\",\"keepassxc-browser@keepassxc.org\":\"69a53c5f-f8fb-46da-81ee-709785a2dae0\",\"default-theme@mozilla.org\":\"55ca0a5f-b6cb-423f-b798-5ef5d81032b7\",\"addons-search-detection@mozilla.com\":\"09131a2a-f687-4bef-a6c9-d44eb925e3bb\",\"google@search.mozilla.org\":\"f7ad8fab-fbd8-4542-ab3f-2493b969d0e1\",\"wikipedia@search.mozilla.org\":\"cf3db87f-8b0a-48f4-a1fd-a20442b0e749\",\"bing@search.mozilla.org\":\"6cd66963-0cb9-4ec3-9aa1-0eff3856d375\",\"ddg@search.mozilla.org\":\"6e6ef5db-8214-4bf3-a69f-70de7a062f8a\",\"amazon@search.mozilla.org\":\"561ade10-eecd-468a-99a1-11bad6212550\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1696777702);
user_pref("media.gmp-manager.buildID", "20230928170531");
user_pref("media.gmp-manager.lastCheck", 1696777702);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking", "{\"slug\":\"opaque-response-blocking-orb-staged-release-rollout\",\"branch\":{\"slug\":\"rollout-single-branch\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"opaqueResponseBlocking\"},\"features\":null},\"active\":true,\"enrollmentId\":\"4103f836-e89d-4f19-b428-9d8d8e6e80f0\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Opaque Response Blocking (ORB) staged release rollout\",\"userFacingDescription\":\"Opaque Response Blocking (ORB) is a security hardening technology that we are rolling out gradually, while we monitor web compatibly.\",\"lastSeen\":\"2023-10-08T15:07:14.769Z\",\"featureIds\":[\"opaqueResponseBlocking\"],\"prefs\":[{\"name\":\"browser.opaqueResponseBlocking\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"enabled\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.filterFetchResponse\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"filterFetchResponse\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.javascriptValidator\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"javascriptValidator\",\"originalValue\":null},{\"name\":\"browser.opaqueResponseBlocking.mediaExceptionsStrategy\",\"branch\":\"user\",\"featureId\":\"opaqueResponseBlocking\",\"variable\":\"mediaExceptionsStrategy\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.enabled", true);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.filterFetchResponse", 2);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.javascriptValidator", true);
user_pref("nimbus.syncdefaultsstore.opaqueResponseBlocking.mediaExceptionsStrategy", 1);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"e21db601-fca0-4027-8110-f11cedc7eb64\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-10-08T15:07:14.832Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "191a5072-b573-4667-a6a9-0c614a0ecde8");
user_pref("services.settings.clock_skew_seconds", 7197);
user_pref("services.settings.last_update_seconds", 1696770467);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1696777631);
user_pref("toolkit.telemetry.cachedClientID", "3432b7c1-6de8-4fd0-910a-e7049248fb12");
user_pref("toolkit.telemetry.previousBuildID", "20230928170531");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
